"""init 6 tables in llm_usage_dashboard schema

Revision ID: 51307b49691d
Revises: 
Create Date: 2026-05-26 11:32:43.451894

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260526_0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_daily_total',
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('prompt_tokens', sa.BigInteger(), nullable=True),
    sa.Column('completion_tokens', sa.BigInteger(), nullable=True),
    sa.Column('cache_read_tokens', sa.BigInteger(), nullable=True),
    sa.Column('cache_write_tokens', sa.BigInteger(), nullable=True),
    sa.Column('total_tokens', sa.BigInteger(), nullable=True),
    sa.Column('request_count', sa.BigInteger(), nullable=True),
    sa.Column('image_count', sa.BigInteger(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('cost_cny', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('complete_vendor_count', sa.Integer(), nullable=False),
    sa.Column('expected_vendor_count', sa.Integer(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), sa.Computed('complete_vendor_count = expected_vendor_count', persisted=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('usage_date'),
    schema='llm_usage_dashboard'
    )
    op.create_index('idx_udt_complete', 'usage_daily_total', ['is_complete'], unique=False, schema='llm_usage_dashboard')
    op.create_table('vendor_ingest_run',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('window_start', sa.Date(), nullable=False),
    sa.Column('window_end', sa.Date(), nullable=False),
    sa.Column('trigger', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('rows_upserted', sa.Integer(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='llm_usage_dashboard'
    )
    op.create_index('idx_run_vendor_started', 'vendor_ingest_run', ['vendor_id', 'started_at'], unique=False, schema='llm_usage_dashboard')
    op.create_index('uniq_running_per_vendor', 'vendor_ingest_run', ['vendor_id'], unique=True, schema='llm_usage_dashboard', postgresql_where=sa.text("status = 'running'"))
    op.create_table('vendor_meta',
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('vendor_type', sa.String(), nullable=False),
    sa.Column('native_currency', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('vendor_id'),
    schema='llm_usage_dashboard'
    )
    op.create_table('vendor_ingest_state',
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('last_ingested_date', sa.Date(), nullable=False),
    sa.Column('last_run_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_run_id'], ['llm_usage_dashboard.vendor_ingest_run.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['llm_usage_dashboard.vendor_meta.vendor_id'], ),
    sa.PrimaryKeyConstraint('vendor_id'),
    schema='llm_usage_dashboard'
    )
    op.create_table('vendor_usage_daily',
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('prompt_tokens', sa.BigInteger(), nullable=True),
    sa.Column('completion_tokens', sa.BigInteger(), nullable=True),
    sa.Column('cache_read_tokens', sa.BigInteger(), nullable=True),
    sa.Column('cache_write_tokens', sa.BigInteger(), nullable=True),
    sa.Column('total_tokens', sa.BigInteger(), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=True),
    sa.Column('image_count', sa.Integer(), nullable=True),
    sa.Column('cost_native', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('cost_cny', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('has_cache_detail', sa.Boolean(), nullable=False),
    sa.Column('last_run_id', sa.BigInteger(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_run_id'], ['llm_usage_dashboard.vendor_ingest_run.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['llm_usage_dashboard.vendor_meta.vendor_id'], ),
    sa.PrimaryKeyConstraint('vendor_id', 'usage_date'),
    schema='llm_usage_dashboard'
    )
    op.create_index('idx_vud_date', 'vendor_usage_daily', ['usage_date'], unique=False, schema='llm_usage_dashboard')
    op.create_table('vendor_model_usage_daily',
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('prompt_tokens', sa.BigInteger(), nullable=True),
    sa.Column('completion_tokens', sa.BigInteger(), nullable=True),
    sa.Column('cache_read_tokens', sa.BigInteger(), nullable=True),
    sa.Column('cache_write_tokens', sa.BigInteger(), nullable=True),
    sa.Column('total_tokens', sa.BigInteger(), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=True),
    sa.Column('image_count', sa.Integer(), nullable=True),
    sa.Column('cost_native', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('cost_cny', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('last_run_id', sa.BigInteger(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_run_id'], ['llm_usage_dashboard.vendor_ingest_run.id'], ),
    sa.ForeignKeyConstraint(['vendor_id', 'usage_date'], ['llm_usage_dashboard.vendor_usage_daily.vendor_id', 'llm_usage_dashboard.vendor_usage_daily.usage_date'], ),
    sa.PrimaryKeyConstraint('vendor_id', 'usage_date', 'model'),
    schema='llm_usage_dashboard'
    )
    op.create_index('idx_vmud_date_model', 'vendor_model_usage_daily', ['usage_date', 'model'], unique=False, schema='llm_usage_dashboard')
    op.create_index('idx_vmud_model', 'vendor_model_usage_daily', ['model'], unique=False, schema='llm_usage_dashboard')
    op.create_index('idx_vmud_vendor_date', 'vendor_model_usage_daily', ['vendor_id', 'usage_date'], unique=False, schema='llm_usage_dashboard')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vmud_vendor_date', table_name='vendor_model_usage_daily', schema='llm_usage_dashboard')
    op.drop_index('idx_vmud_model', table_name='vendor_model_usage_daily', schema='llm_usage_dashboard')
    op.drop_index('idx_vmud_date_model', table_name='vendor_model_usage_daily', schema='llm_usage_dashboard')
    op.drop_table('vendor_model_usage_daily', schema='llm_usage_dashboard')
    op.drop_index('idx_vud_date', table_name='vendor_usage_daily', schema='llm_usage_dashboard')
    op.drop_table('vendor_usage_daily', schema='llm_usage_dashboard')
    op.drop_table('vendor_ingest_state', schema='llm_usage_dashboard')
    op.drop_table('vendor_meta', schema='llm_usage_dashboard')
    op.drop_index('uniq_running_per_vendor', table_name='vendor_ingest_run', schema='llm_usage_dashboard', postgresql_where=sa.text("status = 'running'"))
    op.drop_index('idx_run_vendor_started', table_name='vendor_ingest_run', schema='llm_usage_dashboard')
    op.drop_table('vendor_ingest_run', schema='llm_usage_dashboard')
    op.drop_index('idx_udt_complete', table_name='usage_daily_total', schema='llm_usage_dashboard')
    op.drop_table('usage_daily_total', schema='llm_usage_dashboard')
    # ### end Alembic commands ###
